from __future__ import annotations

NOW = "2026-06-02T00:00:00Z"

DEVICES = [
    {
        "id": "device_toshiba_washer_01",
        "brand": "Toshiba",
        "appliance_type": "washing_machine",
        "model_name": "AW-MVP-01",
        "display_name": "May giat Toshiba mau 1",
        "status": "active",
    },
    {
        "id": "device_panasonic_washer_01",
        "brand": "Panasonic",
        "appliance_type": "washing_machine",
        "model_name": "NA-MVP-01",
        "display_name": "May giat Panasonic mau 1",
        "status": "active",
    },
    {
        "id": "device_daikin_ac_01",
        "brand": "Daikin",
        "appliance_type": "air_conditioner",
        "model_name": "AC-MVP-01",
        "display_name": "Dieu hoa Daikin mau 1",
        "status": "active",
    },
]

TEMPLATES = [
    {
        "id": "template_toshiba_washer_panel_v1",
        "device_id": "device_toshiba_washer_01",
        "template_code": "toshiba_washer_panel_v1",
        "template_image_url": "data/templates/toshiba_washer_panel_v1.txt",
        "logo_bbox": {"x": 20, "y": 10, "width": 120, "height": 40},
        "panel_bbox": {"x": 0, "y": 0, "width": 640, "height": 240},
        "feature_descriptor_path": "data/descriptors/toshiba_washer_panel_v1.npz",
        "version": 1,
        "status": "official",
    },
    {
        "id": "template_panasonic_washer_panel_v1",
        "device_id": "device_panasonic_washer_01",
        "template_code": "panasonic_washer_panel_v1",
        "template_image_url": "data/templates/panasonic_washer_panel_v1.txt",
        "logo_bbox": {"x": 25, "y": 12, "width": 150, "height": 38},
        "panel_bbox": {"x": 0, "y": 0, "width": 640, "height": 240},
        "feature_descriptor_path": "data/descriptors/panasonic_washer_panel_v1.npz",
        "version": 1,
        "status": "official",
    },
    {
        "id": "template_daikin_ac_remote_v1",
        "device_id": "device_daikin_ac_01",
        "template_code": "daikin_ac_remote_v1",
        "template_image_url": "data/templates/daikin_ac_remote_v1.txt",
        "logo_bbox": {"x": 50, "y": 8, "width": 100, "height": 30},
        "panel_bbox": {"x": 0, "y": 0, "width": 320, "height": 720},
        "feature_descriptor_path": "data/descriptors/daikin_ac_remote_v1.npz",
        "version": 1,
        "status": "official",
    },
]

BUTTONS = [
    {
        "id": "btn_toshiba_start",
        "template_id": "template_toshiba_washer_panel_v1",
        "button_id": "start_pause",
        "label": "Start/Pause",
        "vietnamese_name": "Bat dau / Tam dung",
        "function_description": "Bat dau hoac tam dung chu trinh giat",
        "bbox_template_coordinates": {"x": 500, "y": 150, "width": 90, "height": 55},
        "polygon_template_coordinates": None,
        "button_type": "physical",
    },
    {
        "id": "btn_toshiba_quick",
        "template_id": "template_toshiba_washer_panel_v1",
        "button_id": "quick_wash",
        "label": "Quick",
        "vietnamese_name": "Giat nhanh",
        "function_description": "Chon che do giat nhanh",
        "bbox_template_coordinates": {"x": 210, "y": 145, "width": 85, "height": 50},
        "polygon_template_coordinates": None,
        "button_type": "touch",
    },
    {
        "id": "btn_toshiba_dry",
        "template_id": "template_toshiba_washer_panel_v1",
        "button_id": "dry_mode",
        "label": "Dry",
        "vietnamese_name": "Say",
        "function_description": "Chon che do say",
        "bbox_template_coordinates": {"x": 315, "y": 145, "width": 80, "height": 50},
        "polygon_template_coordinates": None,
        "button_type": "touch",
    },
    {
        "id": "btn_panasonic_start",
        "template_id": "template_panasonic_washer_panel_v1",
        "button_id": "start_pause",
        "label": "Start",
        "vietnamese_name": "Bat dau",
        "function_description": "Bat dau chu trinh",
        "bbox_template_coordinates": {"x": 505, "y": 140, "width": 88, "height": 58},
        "polygon_template_coordinates": None,
        "button_type": "physical",
    },
    {
        "id": "btn_panasonic_quick",
        "template_id": "template_panasonic_washer_panel_v1",
        "button_id": "quick_wash",
        "label": "Speedy",
        "vietnamese_name": "Giat nhanh",
        "function_description": "Chon che do giat nhanh",
        "bbox_template_coordinates": {"x": 230, "y": 132, "width": 92, "height": 52},
        "polygon_template_coordinates": None,
        "button_type": "touch",
    },
    {
        "id": "btn_daikin_temp_up",
        "template_id": "template_daikin_ac_remote_v1",
        "button_id": "temp_up",
        "label": "Temp +",
        "vietnamese_name": "Tang nhiet do",
        "function_description": "Tang nhiet do dieu hoa",
        "bbox_template_coordinates": {"x": 180, "y": 235, "width": 70, "height": 55},
        "polygon_template_coordinates": None,
        "button_type": "physical",
    },
]
